# Kubernetes Dynamic Resource Allocation (DRA) Configuration
# Based on requirements from mxl-gst-sink-1080p30-v210
# ResourceClaim
# DRA resource claim

---
apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxl-file-player-1
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mxl-file-player-1
  template:
    metadata:
      labels:
        app: mxl-file-player-1
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: mxl-file-player-container
        image: mxldemo:v1
        imagePullPolicy: Never
        volumeMounts:
            - name: mxl-domain
              mountPath: /dev/shm/mxl
            - name: config-data
              mountPath: /tmp/data
        command: ["/usr/bin/mxl-gst-testsrc"]
        args: ["-v", "/tmp/data/v210_flow.json", "--domain", "/dev/shm/mxl"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1000
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
      volumes:
        - name: mxl-domain
          hostPath:
            path: /dev/shm/mxl # directory location on host
        - name: config-data
          hostPath:
            path: /root/data # directory location on host


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mxl-file-player-2
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mxl-file-player-2
  template:
    metadata:
      labels:
        app: mxl-file-player-2
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: mxl-file-player-container
        image: mxldemo:v1
        imagePullPolicy: Never
        volumeMounts:
            - name: mxl-domain
              mountPath: /dev/shm/mxl
            - name: config-data
              mountPath: /tmp/data
        command: ["/usr/bin/mxl-gst-testsrc"]
        args: ["-v", "/tmp/data/v210_flow_01.json", "--domain", "/dev/shm/mxl"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1000
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
      volumes:
        - name: mxl-domain
          hostPath:
            path: /dev/shm/mxl # directory location on host
        - name: config-data
          hostPath:
            path: /root/data # directory location on host
